foleys_licensing_client: LicensePanel Class Reference
LicensePanel Class Reference
#include <LicensePanel.h>
Public Member Functions
LicensePanel ()
void paint (juce::Graphics &g) override
void resized () override
void update ()
void activate (const juce::String &serial, size_t deactivate)
Additional Inherited Members
Public Attributes inherited from Popup
std::function< void()> onCloseRequest
Constructor & Destructor Documentation
LicensePanel()
LicensePanel () explicit
References activate(), LicenseData::authServerUrl, LicenseData::buyUrl, License::canDemo(), LicenseData::copyright, License::isActivated(), License::isAllowed(), License::isDemo(), LicenseData::manualUrl, Popup::onCloseRequest, License::onLicenseReceived, LicenseData::productName, License::startDemo(), and update().
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
Referenced by update().
update()
void update ()
References activate(), License::canDemo(), License::demoDaysLeft(), License::expires(), License::getActivations(), License::getLastErrorString(), License::isActivated(), License::isAllowed(), License::isDemo(), License::isExpired(), and resized().
Referenced by LicensePanel().
activate()
void activate (const juce::String & serial, size_t deactivate)
References License::activate().
Referenced by LicensePanel(), and update().
The documentation for this class was generated from the following files:
LicensePanel.h
LicensePanel.cpp