foleys_licensing_client: LicensingDemoEditor Class Reference
LicensingDemoEditor Class Reference
#include <LicensingDemoEditor.h>
Inherits AudioProcessorEditor.
Public Member Functions
LicensingDemoEditor (LicensingDemoProcessor &processor)
void paint (juce::Graphics &g) override
void resized () override
Constructor & Destructor Documentation
LicensingDemoEditor()
LicensingDemoEditor (LicensingDemoProcessor & processor) explicit
References License::setPopupWasShown(), License::shouldShowPopup(), and PopupHolder::showPopup().
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
The documentation for this class was generated from the following files:
LicensingDemoEditor.h
LicensingDemoEditor.cpp