foleys_licensing_client: PopupHolder Class Reference
PopupHolder Class Reference
#include <foleys_PopupHolder.h>
Inherits ComponentListener.
Public Member Functions
PopupHolder (juce::Component *parent)
~PopupHolder () override
void showPopup (std::unique_ptr< Popup > popupToShow)
void closePopup ()
void componentMovedOrResized (juce::Component &component, bool wasMoved, bool wasResized) override
Constructor & Destructor Documentation
PopupHolder()
PopupHolder (juce::Component * parent) explicit
~PopupHolder()
~PopupHolder () override
Member Function Documentation
showPopup()
void showPopup (std::unique_ptr< Popup > popupToShow)
References PopupHolder::closePopup().
Referenced by LicensingDemoEditor::LicensingDemoEditor().
closePopup()
void closePopup ()
Referenced by PopupHolder::showPopup().
componentMovedOrResized()
void componentMovedOrResized (juce::Component & component, bool wasMoved, bool wasResized) override
The documentation for this class was generated from the following file:
foleys_PopupHolder.h