foleys_licensing_client: License Class Reference
License Class Reference
#include <foleys_License.h>
Public Member Functions
License ()
~License () override
bool shouldShowPopup ()
Check if a popup should be shown.
void syncLicense ()
Access the server for a new state.
std::string getLastErrorString () const
If the last action resulted in an error, this will return it.
bool isActivated () const
Check if the machine is activated.
bool isExpired () const
Check if the machine is expired (according to server time) This value is cached to be fast and thread safe, but less secure.
bool isAllowed () const
This is a shorthand that either a license that is not expired or a demo is running.
std::optional< std::time_t > expires () const
This returns the expiry time/date or nullopt if it is a perpetual license.
std::string getLicenseeEmail () const
When activated this can be used to display the licensee.
void login (const std::string &email)
Send a login request.
void activate (const std::vector< std::pair< std::string, std::string > > &data)
Request the server to activate this computer.
std::vector< Licensing::Activation > getActivations ()
In case of a failed activation, this contains existing activations for deactivation.
bool canDemo () const
Check if the user is allowed to start a demo.
bool isDemo () const
int demoDaysLeft () const
void startDemo ()
Send a demo request to the server.
void setPopupWasShown (bool wasShown)
Set a flag in the updater to avoid multiple times popup.
void setupLicenseData (const std::filesystem::path &licenseFile, std::string_view hwUID, std::initializer_list< std::pair< std::string, std::string > > data={})
Set the path for the license file.
Static Public Member Functions
static time_t decodeDateTime (const std::string &timeString, const char *formatString)
Public Attributes
std::function< void()> onLicenseReceived
This is called when a valid license was received.
Constructor & Destructor Documentation
License()
License ()
References LicenseUpdater::addObserver(), and LicenseUpdater::fetchIfNecessary().
~License()
~License () override
References LicenseUpdater::removeObserver().
Member Function Documentation
shouldShowPopup()
bool shouldShowPopup () nodiscard
Check if a popup should be shown.
Usually when there is no local license and in demo only once per day.
Returns
References License::isActivated(), License::isAllowed(), and LicenseUpdater::wasPopupShown().
Referenced by LicensingDemoEditor::LicensingDemoEditor().
syncLicense()
void syncLicense ()
Access the server for a new state.
References LicenseUpdater::fetchLicenseData().
getLastErrorString()
std::string getLastErrorString () const nodiscard
If the last action resulted in an error, this will return it.
Returns
the error as string
References LicenseUpdater::getLastErrorString().
Referenced by LicensePanel::update().
isActivated()
bool isActivated () const nodiscard
Check if the machine is activated.
This value is cached to be fast and thread safe, but less secure.
Returns
true if this machine is checked and activated.
Referenced by License::isAllowed(), LicensePanel::LicensePanel(), License::shouldShowPopup(), and LicensePanel::update().
isExpired()
bool isExpired () const nodiscard
Check if the machine is expired (according to server time) This value is cached to be fast and thread safe, but less secure.
Returns
true if the expiry date is in the past.
Referenced by License::isAllowed(), and LicensePanel::update().
isAllowed()
bool isAllowed () const nodiscard
This is a shorthand that either a license that is not expired or a demo is running.
Returns
true if is allowed to run
References License::isActivated(), License::isDemo(), and License::isExpired().
Referenced by LicensePanel::LicensePanel(), LicensingDemoProcessor::processBlock(), License::shouldShowPopup(), and LicensePanel::update().
expires()
std::optional< std::time_t > expires () const
This returns the expiry time/date or nullopt if it is a perpetual license.
Returns
The expiry date
Referenced by LicensePanel::update().
getLicenseeEmail()
std::string getLicenseeEmail () const nodiscard
When activated this can be used to display the licensee.
Returns
the email the license is licensed to
login()
void login (const std::string & email)
Send a login request.
The server will send a login link to the supplied email.
References LicenseUpdater::fetchLicenseData().
activate()
void activate (const std::vector< std::pair< std::string, std::string > > & data)
Request the server to activate this computer.
Parameters
data is a name/value set to add to the request payload.
References LicenseUpdater::fetchLicenseData().
Referenced by LicensePanel::activate().
getActivations()
std::vector< Licensing::Activation > getActivations ()
In case of a failed activation, this contains existing activations for deactivation.
Returns
a list of activated machines
References LicenseUpdater::getActivations().
Referenced by LicenseDeactivate::LicenseDeactivate(), and LicensePanel::update().
canDemo()
bool canDemo () const nodiscard
Check if the user is allowed to start a demo.
Returns
true, if a demo is available. False if the product doesn't offer one or the demo was already used.
Referenced by LicensePanel::LicensePanel(), and LicensePanel::update().
isDemo()
bool isDemo () const nodiscard
Returns
True, if the product is currently running as demo.
Referenced by License::isAllowed(), LicensePanel::LicensePanel(), and LicensePanel::update().
demoDaysLeft()
int demoDaysLeft () const nodiscard
Returns
the number of days left to demo. Will be negative if the demo expired.
Referenced by LicensePanel::update().
startDemo()
void startDemo ()
Send a demo request to the server.
References LicenseUpdater::fetchLicenseData().
Referenced by LicensePanel::LicensePanel().
setPopupWasShown()
void setPopupWasShown (bool wasShown)
Set a flag in the updater to avoid multiple times popup.
Parameters
wasShown
References LicenseUpdater::setPopupWasShown().
Referenced by LicensingDemoEditor::LicensingDemoEditor().
setupLicenseData()
void setupLicenseData (const std::filesystem::path & licenseFile, std::string_view hwUID, std::initializer_list< std::pair< std::string, std::string > > data = {})
Set the path for the license file.
This needs to be called only once
Parameters
licenseFile the filename to store the license to
hwUID the hardware UID of the running system
data a string pair vector of data to send with every payload
References LicenseUpdater::setupLicenseData().
Referenced by LicensingDemoProcessor::LicensingDemoProcessor().
decodeDateTime()
time_t decodeDateTime (const std::string & timeString, const char * formatString) static nodiscard
Referenced by LicenseUpdater::fetchIfNecessary().
Member Data Documentation
onLicenseReceived
std::function<void()> onLicenseReceived
This is called when a valid license was received.
Referenced by LicensePanel::LicensePanel().
The documentation for this class was generated from the following files:
foleys_License.h
foleys_License.cpp