foleys_licensing_client: LicenseUpdater Class Reference
LicenseUpdater Class Reference
The LicenseUpdater is a shared instance from all License classes that handles fetching new licenses to avoid duplicate requests.
#include <foleys_LicenseUpdater.h>
Classes
struct Observer
Each License is an observer to the LicenseUpdater.
Public Types
using Ptr = SharedObject<LicenseUpdater>
Public Member Functions
LicenseUpdater ()
Licensing::Error getLastError () const
If the last action resulted in an error, this will return it.
std::string getLastErrorString () const
If the last action resulted in an error, this will return it.
void fetchIfNecessary (int hours=24)
This method checks if a license file is present and if it was fetched less than 24 hours before.
void fetchLicenseData (std::string_view action={}, const std::vector< std::pair< std::string, std::string > > &data={})
Tries to get new license data from the server.
void addObserver (Observer *observer)
Register an observer when a new license answer is received or loaded.
void removeObserver (Observer *observer)
Deregister an observer.
void setupLicenseData (const std::filesystem::path &licenseFile, std::string_view hwUID, std::initializer_list< std::pair< std::string, std::string > > data)
std::string getContents ()
std::vector< Licensing::Activation > getActivations ()
In case of a failed activation, this contains existing activations for deactivation.
bool wasPopupShown () const
Store a flag if the popup was already shown in that session.
void setPopupWasShown (bool wasShown)
LicenseUpdater (const LicenseUpdater &)=delete
Detailed Description
The LicenseUpdater is a shared instance from all License classes that handles fetching new licenses to avoid duplicate requests.
Member Typedef Documentation
Ptr
using Ptr = SharedObject<LicenseUpdater>
Constructor & Destructor Documentation
LicenseUpdater() [1/2]
LicenseUpdater ()
References LicenseUpdater::fetchIfNecessary().
LicenseUpdater() [2/2]
LicenseUpdater (const LicenseUpdater &) delete
Member Function Documentation
getLastError()
Licensing::Error getLastError () const nodiscard
If the last action resulted in an error, this will return it.
Returns
the error as string
getLastErrorString()
std::string getLastErrorString () const nodiscard
If the last action resulted in an error, this will return it.
Returns
the error as string
Referenced by License::getLastErrorString().
fetchIfNecessary()
void fetchIfNecessary (int hours = 24)
This method checks if a license file is present and if it was fetched less than 24 hours before.
Otherwise it will fetch a new license
References License::decodeDateTime(), LicenseUpdater::fetchLicenseData(), and LicenseUpdater::getContents().
Referenced by License::License(), LicenseUpdater::LicenseUpdater(), and LicenseUpdater::setupLicenseData().
fetchLicenseData()
void fetchLicenseData (std::string_view action = {}, const std::vector< std::pair< std::string, std::string > > & data = {})
Tries to get new license data from the server.
Parameters
action an optional action. Allowed values: 'demo' or 'activate'. Anything else just gets the status
References LicenseData::authServerUrl, foleys::Licensing::CouldNotSave, Crypto::decrypt(), Crypto::encrypt(), foleys::Licensing::NoError, LicenseData::productUid, foleys::Licensing::ServerAnswerInvalid, foleys::Licensing::ServerError, and foleys::Licensing::ServerNotAvailable.
Referenced by License::activate(), LicenseUpdater::fetchIfNecessary(), License::login(), License::startDemo(), and License::syncLicense().
addObserver()
void addObserver (Observer * observer)
Register an observer when a new license answer is received or loaded.
Make sure to removeObserver before you destroy the observer.
Parameters
observer
Referenced by License::License().
removeObserver()
void removeObserver (Observer * observer)
Deregister an observer.
Parameters
observer
Referenced by License::~License().
setupLicenseData()
void setupLicenseData (const std::filesystem::path & licenseFile, std::string_view hwUID, std::initializer_list< std::pair< std::string, std::string > > data)
References LicenseUpdater::fetchIfNecessary().
Referenced by License::setupLicenseData().
getContents()
std::string getContents () nodiscard
References Crypto::decrypt().
Referenced by LicenseUpdater::fetchIfNecessary(), and LicenseUpdater::getActivations().
getActivations()
std::vector< Licensing::Activation > getActivations ()
In case of a failed activation, this contains existing activations for deactivation.
Returns
a list of activated machines
References LicenseUpdater::getContents().
Referenced by License::getActivations().
wasPopupShown()
bool wasPopupShown () const nodiscard
Store a flag if the popup was already shown in that session.
Returns
false if the popup wasn't shown yet
Referenced by License::shouldShowPopup().
setPopupWasShown()
void setPopupWasShown (bool wasShown)
Referenced by License::setPopupWasShown().
The documentation for this class was generated from the following files:
foleys_LicenseUpdater.h
foleys_LicenseUpdater.cpp