foleys_licensing_client: choc::base64 Namespace Reference
choc::base64 Namespace Reference
Functions
template<typename WriteFrameFn >
void encodeToFrames (const void *inputBinaryData, size_t numInputBytes, WriteFrameFn &&writeFrame)
Encodes a chunk of binary data as base-64. The lambda function provided for the output callback must take 4 char parameters, and it will be called for each set of 4 base-64 characters that are produced (the length of a base-64 string is always a multiple of 4).
std::string encodeToString (const void *inputBinaryData, size_t numInputBytes)
Returns a base-64 string for the given chunk of binary data.
template<typename Container >
std::string encodeToString (const Container &)
Returns a base-64 string for a chunk of binary data provided in some kind of container, e.g. a std::vector<uint8_t> or std::string.
template<typename HandleOutputByteFn >
bool decode (std::string_view base64, HandleOutputByteFn &&handleOutputByte)
Attempts to decode a base64 string, calling a lambda to handle each byte that is produced. The lambda should have one parameter which is a uint8_t. Returns false if any errors were encountered before finishing.
template<typename OutputContainer >
bool decodeToContainer (OutputContainer &outputContainer, std::string_view base64)
Attempts to decode a base64 string, writing the results to a container such as a std::vector. The container passed in must have reserve() and a push_back() method that will be called with a uint8_t argument. Returns a bool to indicate success - it'll fail if the data wasn't valid base64.
Function Documentation
encodeToFrames()
template<typename WriteFrameFn > void encodeToFrames (const void * inputBinaryData, size_t numInputBytes, WriteFrameFn && writeFrame)
Encodes a chunk of binary data as base-64. The lambda function provided for the output callback must take 4 char parameters, and it will be called for each set of 4 base-64 characters that are produced (the length of a base-64 string is always a multiple of 4).
Also see choc::base64::encodeToString() for an easier way to get the result as a string.
Referenced by encodeToString().
encodeToString() [1/2]
std::string encodeToString (const void * inputBinaryData, size_t numInputBytes)
Returns a base-64 string for the given chunk of binary data.
References encodeToFrames().
Referenced by encodeToString(), and Crypto::encrypt().
encodeToString() [2/2]
template<typename Container > std::string encodeToString (const Container & c)
Returns a base-64 string for a chunk of binary data provided in some kind of container, e.g. a std::vector<uint8_t> or std::string.
References encodeToString().
decode()
template<typename HandleOutputByteFn > bool decode (std::string_view base64, HandleOutputByteFn && handleOutputByte)
Attempts to decode a base64 string, calling a lambda to handle each byte that is produced. The lambda should have one parameter which is a uint8_t. Returns false if any errors were encountered before finishing.
Referenced by decodeToContainer().
decodeToContainer()
template<typename OutputContainer > bool decodeToContainer (OutputContainer & outputContainer, std::string_view base64)
Attempts to decode a base64 string, writing the results to a container such as a std::vector. The container passed in must have reserve() and a push_back() method that will be called with a uint8_t argument. Returns a bool to indicate success - it'll fail if the data wasn't valid base64.
References decode().
Referenced by Crypto::decrypt().