foleys_licensing_client: LicenseData Namespace Reference
LicenseData Namespace Reference
Variables
const char * productName = (const char*) temp_productName
const char * copyright = (const char*) temp_copyright
const char * version = (const char*) temp_version
const char * authServerUrl = (const char*) temp_authServerUrl
const char * buyUrl = (const char*) temp_buyUrl
const char * manualUrl = (const char*) temp_manualUrl
const char * productUid = (const char*) temp_productUid
const unsigned char * publicKey = (unsigned const char*) temp_publicKey
const unsigned char * privateKey = (unsigned const char*) temp_privateKey
Variable Documentation
productName
const char * productName = (const char*) temp_productName
Referenced by LicensePanel::LicensePanel(), and LicensingDemoProcessor::LicensingDemoProcessor().
copyright
const char * copyright = (const char*) temp_copyright
Referenced by LicensePanel::LicensePanel().
version
const char * version = (const char*) temp_version
Referenced by LicensingDemoProcessor::LicensingDemoProcessor().
authServerUrl
const char * authServerUrl = (const char*) temp_authServerUrl
Referenced by LicenseUpdater::fetchLicenseData(), and LicensePanel::LicensePanel().
buyUrl
const char * buyUrl = (const char*) temp_buyUrl
Referenced by LicensePanel::LicensePanel().
manualUrl
const char * manualUrl = (const char*) temp_manualUrl
Referenced by LicensePanel::LicensePanel().
productUid
const char * productUid = (const char*) temp_productUid
Referenced by LicenseUpdater::fetchLicenseData().
publicKey
const unsigned char * publicKey = (unsigned const char*) temp_publicKey
Referenced by Crypto::decrypt(), and Crypto::encrypt().
privateKey
const unsigned char * privateKey = (unsigned const char*) temp_privateKey
Referenced by Crypto::decrypt(), and Crypto::encrypt().