foleys_licensing_client: Crypto Struct Reference
Crypto Struct Reference
#include <foleys_Crypto.h>
Static Public Member Functions
static std::string decrypt (std::string_view cipher)
Decrypts a message.
static std::string encrypt (std::string_view message)
Encrypts a message.
Member Function Documentation
decrypt()
std::string decrypt (std::string_view cipher) static
Decrypts a message.
The cipher is encoded in base64 and starts with NONCE_BYTES of a random nonce
Parameters
cipher
Returns
the plain text
References choc::base64::decodeToContainer(), LicenseData::privateKey, and LicenseData::publicKey.
Referenced by LicenseUpdater::fetchLicenseData(), and LicenseUpdater::getContents().
encrypt()
std::string encrypt (std::string_view message) static
Encrypts a message.
The returned cipher is wrapped into base64
Parameters
message
Returns
a base64 encoded cipher
References choc::base64::encodeToString(), LicenseData::privateKey, and LicenseData::publicKey.
Referenced by LicenseUpdater::fetchLicenseData().
The documentation for this struct was generated from the following files:
foleys_Crypto.h
foleys_Crypto.cpp