//
// Created by Daniel Walz on 12.08.24.
//

#ifndef FOLEYS_LICENSING_CLIENT_FOLEYS_SYSTEMINFO_H
#define FOLEYS_LICENSING_CLIENT_FOLEYS_SYSTEMINFO_H

#endif  // FOLEYS_LICENSING_CLIENT_FOLEYS_SYSTEMINFO_H
