//
// This file was auto-generated by the license server
//

#pragma once

namespace LicenseData
{

const char* authServerUrl = "http://test.foleysfinest.com:8000/auth/";
const char* buyUrl = "https://foleysfinest.com/";
const char* productUid = "adsfdsfadfs";


}
