//
// This file was auto-generated by the license server
//


#include "private/foleys_LicenseData.h"

namespace LicenseData
{

const char* authServerUrl = "http://test.foleysfinest.com:8000/auth/";
const char* buyUrl = "https://foleysfinest.com/";
const char* productUid = "adsfdsfadfs";


}
